config/routes.rb
Rails.application.routes.draw do
  
  root to: "homes#top"
  get 'home/about' => 'homes#about', as: 'about'
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:index, :show, :edit, :create, :update, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to:user
  belongs_to:book
  
  validates :comment, presence: true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
  validates :message, length: { in: 1..140 }  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/group.rb
class Group < ApplicationRecord
# グループ機能
  has_many :group_users, dependent: :destroy
  belongs_to :owner, class_name: 'User'
  has_many :users, through: :group_users
  
  validates :name, presence: true
  validates :introduction, presence: true
  has_one_attached :image

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/monbo.jpeg')
      image.attach(io: File.open(file_path), filename: 'monbo.jpeg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end



#オーナーかどうかチェックする
  def is_owned_by?(user)
      owner.id == user.id
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  # class_name: "User"でUserモデルを参照
  # belongs_to :user　と指定すると、どっちがどっちのuserかわからなくなるため
  # follower, followedで分けてあげる
  # しかし、そのままだとfollower, followedテーブルを探しに行くので、
  # class_name: "User"とすることで、userテーブルからデータを取ってくるようにする。
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates_uniqueness_of :follower_id, scope: :followed_id
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image


  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/monbo.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'monbo.jpeg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

# Userモデルに関連するフォロー・フォロワー機能の定義

# フォローされているユーザーに対する関連付け
# Relationshipモデルのfollowed_idカラムを参照して、逆方向の関連を持つ
has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
# 上記の関連を経由して、実際にフォローしているユーザー情報を取得
has_many :followers, through: :reverse_of_relationships, source: :follower

# フォローしているユーザーに対する関連付け
# Relationshipモデルのfollower_idカラムを参照して、関連を持つ
has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
# 上記の関連を経由して、実際にフォローされているユーザー情報を取得
has_many :followings, through: :relationships, source: :followed
# グループ機能
has_many :group_users, dependent: :destroy


# ユーザーをフォローするメソッド
# @param [User] user - フォローするユーザー
# @return [Relationship] - 作成されたフォロー関係
def follow(user)
  relationships.create(followed_id: user.id)
end

# ユーザーのフォローを解除するメソッド
# @param [User] user - フォローを解除するユーザー
# @return [Relationship, nil] - 削除されたフォロー関係、またはnil
def unfollow(user)
  relationships.find_by(followed_id: user.id)&.destroy
end

# 指定したユーザーをフォローしているか確認するメソッド
# @param [User] user - チェック対象のユーザー
# @return [Boolean] - フォローしている場合はtrue、それ以外はfalse
def following?(user)
  followings.include?(user)
end

# 検索方法分岐用メソッド
def self.looks(search, word)
  if search == "perfect_match"
    @user = User.where("name LIKE?", "#{word}")
  elsif search == "forward_match"
    @user = User.where("name LIKE?","#{word}%")
  elsif search == "backward_match"
    @user = User.where("name LIKE?","%#{word}")
  elsif search == "partial_match"
    @user = User.where("name LIKE?","%#{word}%")
  else
    @user = User.all
  end
end



  validates :name, uniqueness: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
 belongs_to :user
 belongs_to :book
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if model.errors.any? %>
  <%= model.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_footer.html.erb
 <div class="container mt-5">
   <div class="row">
     <div class="mx-auto">CopyRight Infratop.inc</div>
   </div>
</div>

app/views/layouts/_header.html.erb
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Bookers</a>
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li>
                <%= link_to user_path(current_user), class: "nav-link text-light" do %>
                <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li>
                <%= link_to users_path, class: "nav-link text-light" do %>
                <i class="fas fa-users"></i> Users
                <% end %>
              </li>
              <li>
                <%= link_to books_path, class: "nav-link text-light" do %>
                <i class="fas fa-book-open"></i> Books
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
                <i class="fas fa-sign-out-alt"></i> Log out
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to root_path, class: "nav-link text-light" do %>
                <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li>
                <%= link_to about_path, class: "nav-link text-white" do %>
                <i class="fas fa-link"></i> About
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path, class: "nav-link text-white" do %>
                <i class="fas fa-user-plus"></i> Sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path, class: "nav-link text-white" do %>
                <i class="fas fa-sign-in-alt"></i> Log in
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2P2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/8f0aef17a7.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
   </header>
    <div class="row">
  <div class="col-md-6">
    <%= render 'searches/search' %>
  </div>
  <div class="col-md-6">
    <%= render 'tagsearches/tagsearch' %>
  </div>
</div>
                 
    <%= flash[:notice] %>
    <%= yield %>
    <footer>
       <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>